// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnwbjhuaafklcredknbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNud2JqaHVhYWZrbGNyZWRrbmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2NTEwNTAsImV4cCI6MjA1MDIyNzA1MH0.5zvnFWFc3mDQ2INBg6CwgWwxfboUAMJF0zU1j-TE8AY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);